// examples/react-ts/App.tsx
import "olloweditor/styles.css";
import { OllowEditor } from "olloweditor/react";

export default function App() {
  return (
    <OllowEditor
      options={{ theme: "auto", persistTheme: true }}
      textareaProps={{ name: "body", placeholder: "Start writing..." }}
      onChange={(value) => {
        console.log(value);
      }}
    />
  );
}

// examples/vue/App.vue
<script setup>
import "olloweditor/styles.css";
import OllowEditor from "olloweditor";
import { onMounted } from "vue";

onMounted(() => {
  OllowEditor.init("#editor", {
    theme: "auto",
    persistTheme: true,
  });
});
</script>

<template>
  <textarea id="editor" name="body" data-nw-editor />
</template>
